### ISSUE TITLE
내부 디렉토리 변경

### ISSUE THREAD

**Issue by ppsrac** [I-see-the-algorithm/I-see-the-algorithm#2]
`Homepage.js`나 이런 페이지들의 부모 디렉토리를 Screen으로 두고 routes에는 `navigation.js`같은 것들을 넣어두는 것은 어떤가요.

**Comment by wnwoghd22** [comment]
보통 이런 건 컨벤션이 어떻게 되는지는 모르겠네요.
계층 깊이가 크게 깊어지지 않는다면 전 상관 없습니다.

**Comment by ppsrac** [comment]
그럼 일단 develop branch에 Screen으로 바꿔서 커밋해놓을게요?
나중에 navigation.js만들면 그 파일은 navigation 디렉토리에 넣어두죠
